version: "3.8"

services:
  frontend:
    build:
      context: frontend
    ports:
      - 9090:80
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
    environment:
      H2_FILE_PATH: /app/cook_data/database
    volumes:
      - type: bind
        source: /f/work/cook_data
        target: /app/cook_data
