apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: backend
    context: ../
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - ../kubernetes/deployment.yaml
  - ../kubernetes/service.yaml
