apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cook
data:
  nginx-ui.conf: |
    upstream Backend {
      server backend:8080;
    }

    server {
      listen 80;
      listen [::]:80;
      root /var/www/html/;
      index index.html;

      location / {
          try_files $uri $uri/ /index.html;
      }

      location /api/ {
          proxy_pass http://Backend;
      }
    }
    