apiVersion: v1
kind: Service
metadata:
  namespace: cook
  annotations:
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
