apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: frontend
    context: ../
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - ../kubernetes/configmap.yaml
  - ../kubernetes/deployment.yaml
  - ../kubernetes/service.yaml
