CREATE TABLE IF NOT EXISTS RECIPES(
    id IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS INGREDIENTS(
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    amount VARCHAR(255),
    measurement VARCHAR(255),
    recipe_id INT
);
